GET http://localhost:9000/

###

POST http://localhost:9000/login
Content-Type: application/json

{
    "username": "anurag"
}

###

GET http://localhost:9000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkzNzAzOTh9.3u9wRVbtryJsQdSO-nrdoapejwqtCQ42jHt545qwQaI
Content-Type: application/json

{

}

###
GET http://localhost:9000/product/PROD_1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkzNzAzOTh9.3u9wRVbtryJsQdSO-nrdoapejwqtCQ42jHt545qwQaI
Content-Type: application/json

{

}

###
POST http://localhost:9000/addProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkzNzAzOTh9.3u9wRVbtryJsQdSO-nrdoapejwqtCQ42jHt545qwQaI
Content-Type: application/json

{
    "id": "PROD_5",
    "name": "Product 5",
    "price": "290$"
}

###
PATCH http://localhost:9000/editProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkzNzAzOTh9.3u9wRVbtryJsQdSO-nrdoapejwqtCQ42jHt545qwQaI
Content-Type: application/json

{
    "id": "PROD_5",
    "update": {
        "name": "Food Item",
        "price": "390$"
    }
}

###
DELETE http://localhost:9000/deleteProduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkzNzAzOTh9.3u9wRVbtryJsQdSO-nrdoapejwqtCQ42jHt545qwQaI
Content-Type: application/json

{
    "id": "PROD_5"
}